# .github/workflows/vibe-coding-digest.yml
name: Daily Vibe Coding Digest

on:
  push:
  schedule:
    # Runs once a day at 9AM US Eastern Time (13:00 UTC), note: UTC time does not account for daylight saving time
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  # --- Secrets Scanning Job (Gitleaks) ---
  secrets-scan:
    name: Scan for Secrets (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Run Gitleaks secrets scan
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
        # If secrets are found, this job will fail and block downstream jobs
    # Traceability: Implements CI/CD secret scanning per .cicdrules.md ("build quality in" and security automation)

  fetch-and-email-digest:
    runs-on: ubuntu-latest
    needs: [secrets-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # --- FAKE SECRETS FOR TESTING GITLEAKS ---
      # AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      # GITHUB_TOKEN = "ghp_FAKEgitleaksToken1234567890abcdefgHIJKL"
      # FAKE_API_KEY = "sk-test_51H8zF1FAKEKEYEXAMPLE1234567890abcdef"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai requests

      - name: Run Digest Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          GITHUB_TOKEN: ghp_FAKEgitleaksToken1234567890abcdefgHIJKL
          FAKE_API_KEY: sk-test_51H8zF1FAKEKEYEXAMPLE1234567890abcdef
        run: python .github/scripts/vibe_digest.py
